# Generated by Django 4.0.3 on 2022-04-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_lasttname_user_lastname_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='SOS_USER',
        ),
    ]
