# Generated by Django 4.0.3 on 2022-05-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_rollnumber_marksheet_rollnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subjectDescription',
            new_name='subjectDiscription',
        ),
    ]
