# Generated by Django 4.0.3 on 2022-05-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_subjectdescription_subject_subjectdiscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='adderess',
            new_name='address',
        ),
    ]
