# Generated by Django 4.1.7 on 2023-04-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_rename_adderess_faculty_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Marksheet',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TImeTable',
        ),
    ]
