# Generated by Django 4.1.7 on 2023-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_delete_basemodel_delete_college_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('ConfirmPassword', models.CharField(max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=20)),
                ('Zip', models.IntegerField()),
                ('Country', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'SOS_USERDATA',
            },
        ),
    ]
